### PR TITLE
Add auto-update workflow

### PR DESCRIPTION
**Pull request by jonashaag**

### CODE REVIEW

**Comment by xhochy** [comment]
It's probably simpler to use the Anaconda API directly instead of using mamba, you can take inspiration from https://github.com/conda-forge/miniforge/blob/main/.github/workflows/conda_release.yml

**Comment by jonashaag** [comment]
> It's probably simpler to use the Anaconda API directly instead of using mamba

I tried that in the past and it grew into a huge codebase, I want to try a very simple approach here. Maybe the previous approach was over engineered https://github.com/Quantco/.github/tree/master/workflow-templates https://github.com/Quantco/github-actions/tree/update-conda-dependencies/update-conda-dependencies

**Comment by xhochy** [comment]
Yes, that is a bit overengineered. I would expect this to be simpler than the one I've written for the conda action. My approach would be

1. Write a JavaScript action that fetches the current version and writes the environment.yml
2. Use https://github.com/conda-forge/miniforge/blob/c62a54605a63522514effe10ccf0d6b2bb2863d2/.github/workflows/autoupdate.yml#L17-L32 to make a PR on a change.

**Comment by jonashaag** [comment]
@xhochy this seems to work and I think it's even simpler

**Review by xhochy — APPROVED** [review]

**Pull request merged**
